#!/usr/bin/env python3
"""Plots related to a Fe55 (or other) source peak (HistOcc and HistToT not required)."""
import argparse
import glob
import os
import traceback
from matplotlib.backends.backend_pdf import PdfPages
import matplotlib.pyplot as plt
import numpy as np
import tables as tb
from tqdm import tqdm
from plot_utils_pisa import *


def main(input_files, overwrite=False, output_file=None):
    if output_file is None:
        output_file = os.path.splitext(input_files[0])[0] + "_peak.pdf"
    if os.path.isfile(output_file) and not overwrite:
        return

    # Prepare histogram
    counts = np.zeros((512, 512, 128))
    cfg = []

    for input_file in tqdm(input_files, disable=len(input_files)<2):
        print("Processing", input_file)
        with tb.open_file(input_file) as f:
            cfg.append(get_config_dict(f))

            # Process 16M hits at a time
            csz = 2**24
            n_hits = f.root.Dut.shape[0]
            for i_first in tqdm(range(0, n_hits, csz), unit="chunk", disable=n_hits/csz<=1):
                i_last = min(i_first + csz, n_hits)
                hits = f.root.Dut[i_first:i_last]
                # TODO Filter only isolated hits?
                with np.errstate(all='ignore'):
                    tmp, edges = np.histogramdd(
                        (hits["col"], hits["row"], (hits["te"] - hits["le"]) & 0x7f),
                        bins=[512, 512, 128], range=[[0, 512], [0, 512], [0, 128]])
                    counts += tmp
                    del tmp
            del hits

    with PdfPages(output_file) as pdf:
        plt.figure(figsize=(6.4, 4.8))

        if len(input_files) > 1:
            plt.annotate(
                split_long_text(
                    "This file was generated by joining the following\n\n"
                    + "\n".join(input_files)
                    ), (0.5, 0.5), ha='center', va='center')
            plt.gca().set_axis_off()
            pdf.savefig(); plt.clf()

        for input_file, c in zip(input_files, cfg):
            draw_summary(input_file, c)
            pdf.savefig(); plt.clf()
        # print("Summary")

        # Find the position of the peak in each pixel
        max_tot = np.argmax(counts, axis=2)

        # Peak center distribution
        for fc, lc, name in FRONTENDS:
            plt.hist(max_tot[fc:lc+1,:].reshape(-1), bins=128, range=[0, 128],
                     histtype='step', label=name, rasterized=True)
        plt.xlabel("ToT of max [25 ns]")
        plt.ylabel("Pixels / bin")
        plt.title("ToT bin with the most entries (approx. peak)")
        plt.legend()
        plt.grid()
        pdf.savefig(); plt.clf()

        plt.close()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "input_file", nargs="*",
        help="The _source_scan_interpreted.h5 file(s). If not given, looks in output_data/module_0/chip_0.")
    parser.add_argument("-f", "--overwrite", action="store_true",
                        help="Overwrite plots when already present.")
    parser.add_argument("-j", "--join", metavar="OUTPUT_FILE.PDF", default=None,
                        help="Join all input files and put results in the given PDF.")
    args = parser.parse_args()

    files = []
    if args.input_file:  # If anything was given on the command line
        for pattern in args.input_file:
            files.extend(glob.glob(pattern, recursive=True))
    else:
        files.extend(glob.glob("output_data/module_0/chip_0/*_source_scan_interpreted.h5"))
    files.sort()

    if args.join is None:
        for fp in tqdm(files):
            try:
                main([fp], args.overwrite)
            except Exception:
                print(traceback.format_exc())
    else:
        main(files, args.overwrite, args.join)
